services:
  d20:
    image: d20:latest
    container_name: d20_bot
    build: .
    environment:
      - TG_TOKEN=${TG_TOKEN}
    restart: always
    resources:
      limits:
        cpu: '0.01'
        memory: 50M
