services:
  d20:
    image: d20:latest
    container_name: d20_bot
    build: .
    environment:
      - TG_TOKEN=${TG_TOKEN}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 150M
        reservations:
          cpus: '0.005'
          memory: 20M
