{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "d20-bot.fullname" . }}
  labels:
    {{- include "d20-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  D20_BOT_TG_TOKEN: {{ required "secrets.telegramToken is required when existingSecret is empty" .Values.secrets.telegramToken | quote }}
  {{- if .Values.core.enabled }}
  D20_BOT_CORE_TOKEN: {{ required "secrets.coreToken is required when Core is enabled and existingSecret is empty" .Values.secrets.coreToken | quote }}
  {{- end }}
{{- end }}
