name: Run bot
on: [push]

jobs:
  run:
    runs-on: [self-hosted, raspberry]
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: iammushroom/d20_bot:latest
          context: .
      - name: Run
        run: docker compose up -d
