name: Run bot
on: [push]

jobs:
  run:
    runs-on: [self-hosted, raspberry]
    environment: prd
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug
        run: echo $TG_TOKEN > /tmp/token.txt
      # - name: Stop docker compose
      #   run: docker compose down
      # - name: Build image
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: false
      #     tags: iammushroom/d20_bot:latest
      #     context: .
      # - name: Run
      #   run: docker compose up -d
