name: Run bot
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/push_image.yaml'

jobs:
  prepare:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ github.ref_name }}
    outputs:
      branch: ${{ steps.set_variables.outputs.branch }}
      tag: ${{ steps.set_variables.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        shell: bash
        run: |
          BRANCH=$(git branch | grep '*' | cut -d' ' -f2)
          echo "branch=$BRANCH"
          if [[ $BRANCH == 'dev' ]]; then TAG=$(git rev-parse --short "$GITHUB_SHA"); else TAG='latest'; fi
          echo "tag=$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        id: set_variables
      - name: Stop docker compose
        run: docker compose -p "d20_bot_${{ steps.set_variables.outputs.branch }}" down
  build:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ needs.prepare.outputs.branch }}
    needs:
      - prepare
    steps:
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: immushroom/d20_bot:${{ needs.prepare.outputs.tag }}
          context: .
  run:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ needs.prepare.outputs.branch }}
    needs:
      - prepare
      - build
    steps:
      - name: Run
        env:
          DOCKER_TAG: ${{ needs.prepare.outputs.tag }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: docker compose -p "d20_bot_${{ needs.prepare.outputs.branch }}" up -d
      - name: Prune unused images
        run: echo 'y' | docker image prune
