name: Run bot
on: [push]

jobs:
  run:
    runs-on: [self-hosted, raspberry]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Stop docker compose
        run: docker compose down
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: immushroom/d20_bot:latest
          context: .
      - name: Run
        environment: ${{ steps.extract_branch.outputs.branch }}
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: docker compose up -d -p "d20_bot_${{ steps.extract_branch.outputs.branch }}"
