name: Run bot
on: [push]

jobs:
  prepare:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ github.ref_name }}
    outputs:
      branch: ${{ steps.set_variables.outputs.branch }}
      tag: ${{ steps.set_variables.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        shell: bash
        run: |
          if [[$BRANCH == 'prd']]; then TAG='latest'; else TAG=$(git rev-parse --short "$GITHUB_SHA"); fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$(git branch -r --contains ${{ github.ref }}) --format "%(refname:lstrip=3)"" >> $GITHUB_OUTPUT
        id: set_variables
      - name: Stop docker compose
        run: docker compose -p "d20_bot_${{ steps.set_variables.outputs.branch }}" down
  build:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ needs.prepare.outputs.branch }}
    needs:
      - prepare
    steps:
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: immushroom/d20_bot:${{ needs.prepare.outputs.tag }}
          context: .
  run:
    runs-on: [self-hosted, raspberry]
    environment:
      name: ${{ needs.prepare.outputs.branch }}
    needs:
      - prepare
      - build
    steps:
      - name: Run
        env:
          DOCKER_TAG: ${{ needs.prepare.outputs.tag }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: docker compose -p "d20_bot_${{ needs.prepare.outputs.branch }}" up -d
      - name: Prune unused images
        run: echo 'y' | docker image prune
